### ISSUE TITLE
Statically link the WebView2 loader library

### ISSUE THREAD

**Issue by matonga** [jchv/webview2-in-mingw#4]
This is more sort of a feature request... could it be possible to make this:

https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/static

But for MinGW? The intended result would be to statically link libgcc, stdc++ (already demonstrated in the Makefile, thank you for that one) and the WebView2 loader library, thus only one file to distribute instead of two (.exe and WebView2Loader.dll)

Anyway, thanks for webview2-in-mingw, and best regards from a user happily cross-compiling WebView2 apps from a Linux machine :-)

**Comment by jchv** [comment]
Maybe this would be of interest?

https://github.com/jchv/OpenWebView2Loader

It could be made to compile with MinGW.

**Comment by theseyan** [comment]
+1
I'm currently trying to statically link WebView2Loader into a MinGW project and the official loader has no way to do this. Would love if you documented the instructions on how to compile OpenWebView2Loader with MinGW.

**Comment by jchv** [comment]
A while ago I did in fact update OpenWebView2Loader and it should compile fine with MSys2 + MinGW. Feel free to reopen this issue or create more issues if there are further problems. Thanks!
